buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        mavenLocal()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:9.2.1')
        classpath( 'com.google.gms:google-services:4.4.4')
        classpath 'org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.20'
        classpath( "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20")
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        mavenLocal()
    }
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}
