buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.0'
        classpath 'com.google.gms:google-services:4.4.3'
    }
}

allprojects {
    repositories {

        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
        }
    }
}

tasks.register('clean', Delete) {
    delete getLayout().getBuildDirectory()
}
